SET FOREIGN_KEY_CHECKS=0;

INSERT INTO colors (id, title) VALUES
(1, 'Zila'),
(2, 'Nav noteikta'),
(3, 'Sarkana'),
(4, 'Gaiši brūna'),
(5, 'Gaiši zila'),
(6, 'Pelēka'),
(7, 'Dzeltena'),
(8, 'Zaļa'),
(9, 'Oranža'),
(10, 'Brūna'),
(11, 'Ķiršu'),
(12, 'Tumši dzeltena'),
(13, 'Melna'),
(14, 'Tumši brūna'),
(15, 'Balta'),
(16, 'Gaiši pelēka'),
(17, 'Gaiši dzeltena'),
(18, 'Tumši zila'),
(19, 'Tumši pelēka'),
(20, 'Tumši zaļa'),
(21, 'Gaiši zaļa'),
(22, 'Violeta'),
(23, 'Rozā'),
(24, 'Vairākkrāsu'),
(25, 'Violeta toņmaiņas'),
(26, 'Kamuflēta'),
(27, 'Oranža toņmaiņas'),
(28, 'Pelēka toņmaiņas'),
(29, 'Zila toņmaiņas'),
(30, 'Melna toņmaiņas'),
(31, 'Tumši violeta'),
(32, 'Balta toņmaiņas'),
(33, 'Sarkana toņmaiņas'),
(34, 'Zaļa toņmaiņas'),
(35, 'Dzeltena toņmaiņas'),
(36, 'Brūna toņmaiņas');
